### ISSUE TITLE
Extended class issue

### ISSUE THREAD

**Issue by denisrehacek** [beranradek/formio#5]
I've got following exception while trying to make FormMapping object like this 
public static final FormMapping<Romania> romaniaFormMapping = Forms.automatic(Romania.class, "romania").build();

The parrent class of Romania has field id, which Romania doesn't have.

The exception:
SEVERE: Servlet.service() for servlet [tangle] in context with path [/eon] threw exception [Servlet execution threw an exception] with root cause
java.lang.NoSuchFieldException: id
	at java.lang.Class.getDeclaredField(Unknown Source)
	at net.formio.AbstractFormElement.isRequired(AbstractFormElement.java:131)
	at net.formio.AbstractFormElement.isRequired(AbstractFormElement.java:121)
	at net.formio.BasicFormMappingBuilder.checkRequired(BasicFormMappingBuilder.java:562)
	at net.formio.BasicFormMappingBuilder.checkValidFormMapping(BasicFormMappingBuilder.java:552)
	at net.formio.BasicFormMappingBuilder.buildInternal(BasicFormMappingBuilder.java:445)
	at net.formio.BasicFormMappingBuilder.build(BasicFormMappingBuilder.java:376)
	at net.formio.BasicFormMappingBuilder.build(BasicFormMappingBuilder.java:366)
	at cz.etnetera.eon.ega.ui.EgaProjectEditorLegendComponent.<clinit>(EgaProjectEditorLegendComponent.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.twinstone.tiles.asi.DefaultInstantiator.instantiate(DefaultInstantiator.java:18)
	at org.twinstone.jnpng.app.setups.BeanInstantiator.instantiate(BeanInstantiator.java:26)
	at org.twinstone.tangle.beads.BeadBase.instantiate(BeadBase.java:159)
	at org.twinstone.tangle.beads.BeadChildInstance.instantiate(BeadChildInstance.java:29)
	at org.twinstone.tiles.bi.BeanChildInstance.initialize(BeanChildInstance.java:190)
	at org.twinstone.tiles.bi.BeanInitializer.performPhase(BeanInitializer.java:165)
	at org.twinstone.tiles.bi.BeanInitializer.initializeBean(BeanInitializer.java:155)
	at org.twinstone.tiles.bi.BeanInitializerFeature.initializeInstance(BeanInitializerFeature.java:45)
	at org.twinstone.tangle.beads.BeadBase$DefaultBehavior.initChildren(BeadBase.java:620)
	at org.twinstone.tangle.beads.BeadAspect.initChildren(BeadAspect.java:207)
	at org.twinstone.tangle.beads.BeadBase.initChildren(BeadBase.java:426)
	at org.twinstone.tangle.components.general.SwitchingComponent.initChildren(SwitchingComponent.java:147)
	at cz.etnetera.eon.ega.ui.EgaProjectSwitchingComponent.initChildren(EgaProjectSwitchingComponent.java:16)
	at org.twinstone.tangle.beads.BeadBase.burden(BeadBase.java:463)
	at org.twinstone.tangle.beads.BeadBase.addChild(BeadBase.java:349)
	at org.twinstone.tangle.beads.BeadChildInstance.performPhase(BeadChildInstance.java:42)
	at org.twinstone.tiles.bi.BeanChildInstance.initialize(BeanChildInstance.java:195)
	at org.twinstone.tiles.bi.BeanInitializer.performPhase(BeanInitializer.java:165)
	at org.twinstone.tiles.bi.BeanInitializer.initializeBean(BeanInitializer.java:155)
	at org.twinstone.tiles.bi.BeanInitializerFeature.initializeInstance(BeanInitializerFeature.java:45)
	at org.twinstone.tangle.beads.BeadBase$DefaultBehavior.initChildren(BeadBase.java:620)
	at org.twinstone.tangle.beads.BeadAspect.initChildren(BeadAspect.java:207)
	at org.twinstone.tangle.beads.BeadAspect.initChildren(BeadAspect.java:207)
	at org.twinstone.jnpng.ui.dialog.DialogHostTangleAspect.initChildren(DialogHostTangleAspect.java:102)
	at org.twinstone.tangle.beads.BeadBase.initChildren(BeadBase.java:426)
	at org.twinstone.jnpng.ui.JnpTanglePage.initChildren(JnpTanglePage.java:82)
	at cz.etnetera.eon.ega.ui.RomaniaProjectPanel.initChildren(RomaniaProjectPanel.java:27)
	at org.twinstone.tangle.beads.BeadBase.burden(BeadBase.java:463)
	at org.twinstone.jnpng.ui.JnpTangle.burden(JnpTangle.java:156)
	at org.twinstone.tangle.impl.TangleExecutorBase.burden(TangleExecutorBase.java:140)
	at org.twinstone.tangle.servlet.TangleServletExecutor.execute(TangleServletExecutor.java:276)
	at org.twinstone.jnpng.app.TangleServlet.lambda$service$0(TangleServlet.java:35)
	at org.twinstone.jnpng.app.TangleServlet$$Lambda$34/1072374240.execute(Unknown Source)
	at org.twinstone.jnpng.ds.impl.UniversalStorageDelegate.lambda$withStorageVoid$319(UniversalStorageDelegate.java:47)
	at org.twinstone.jnpng.ds.impl.UniversalStorageDelegate$$Lambda$35/2062133369.execute(Unknown Source)
	at org.twinstone.jnpng.ds.impl.UniversalStorageDelegate.withStorage(UniversalStorageDelegate.java:35)
	at org.twinstone.jnpng.ds.impl.UniversalStorageDelegate.withStorageVoid(UniversalStorageDelegate.java:50)
	at org.twinstone.jnpng.app.TangleServlet.service(TangleServlet.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.twinstone.jnpng.app.LoginFilter.doFilterImpl(LoginFilter.java:113)
	at org.twinstone.jnpng.app.LoginFilter.doFilter(LoginFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.twinstone.servlet.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:74)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.twinstone.servlet.MultipartFilter.doFilter(MultipartFilter.java:151)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.twinstone.jnpng.setup.storage.LoggingFilter.doFilter(LoggingFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.twinstone.jnpng.setup.storage.StorageFilter.doFilter(StorageFilter.java:54)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.twinstone.jnpng.ui.cms.output.OutputFilter.doFilter(OutputFilter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.twinstone.jnpng.app.setups.prof.ProfilingFilter.doFilter(ProfilingFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.twinstone.jnpng.app.srvl.load.LoadMonitorFilter.doFilter(LoadMonitorFilter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by beranradek** [comment]
Now the required flag (annotation) is checked also on getters and missing declared field in subclass does not cause an exception. Fix is available in version 1.6.1.
